spring.application.name=SkillLink

spring.datasource.username=${PG_USERNAME}
spring.datasource.password=${PG_PASSWORD}
spring.datasource.url=${PG_URL}

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
