spring.application.name=demo

spring.datasource.username=${PG_USERNAME}
spring.datasource.password=${PG_PASSWORD}
spring.datasource.url=${PG_URL}

spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true
